import uuid
from datetime import datetime
from sqlalchemy import Column, String, Boolean, Integer, Text, ForeignKey, DateTime, JSON
from sqlalchemy.orm import relationship
from app.database import Base
import json as json_lib

class User(Base):
    __tablename__ = "users"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    email = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    full_name = Column(String)
    settings = Column(JSON, default={})
    created_at = Column(DateTime, default=datetime.utcnow)

    resumes = relationship("Resume", back_populates="user", cascade="all, delete-orphan")
    projects = relationship("Project", back_populates="user", cascade="all, delete-orphan")
    applications = relationship("Application", back_populates="user", cascade="all, delete-orphan")

class Resume(Base):
    __tablename__ = "resumes"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, ForeignKey("users.id"))
    version_name = Column(String)
    content = Column(Text, nullable=False)
    is_base = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    user = relationship("User", back_populates="resumes")
    applications = relationship("Application", back_populates="resume")

class Job(Base):
    __tablename__ = "jobs"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    source = Column(String, nullable=False)
    external_id = Column(String)
    url = Column(Text, unique=True, nullable=False)
    title = Column(String, nullable=False)
    company = Column(String, nullable=False)
    location = Column(String)
    posted_date = Column(DateTime)
    raw_text = Column(Text)
    parsed_data = Column(JSON)
    match_score = Column(Integer)
    is_scam = Column(Boolean, default=False)
    scam_score = Column(Integer)  # Scam probability score (0-100)
    scam_flags = Column(JSON, default=list)  # List of scam indicators detected
    scraped_at = Column(DateTime, default=datetime.utcnow)

    applications = relationship("Application", back_populates="job")
    projects = relationship("Project", back_populates="job")

class Project(Base):
    __tablename__ = "projects"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, ForeignKey("users.id"))
    job_id = Column(String, ForeignKey("jobs.id"), nullable=True)
    title = Column(String, nullable=False)
    description = Column(Text)
    tech_stack = Column(JSON)
    link = Column(Text)
    is_autogenerated = Column(Boolean, default=False)
    metadata_json = Column(JSON)
    added_at = Column(DateTime, default=datetime.utcnow)

    user = relationship("User", back_populates="projects")
    job = relationship("Job", back_populates="projects")

class Application(Base):
    __tablename__ = "applications"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, ForeignKey("users.id"))
    job_id = Column(String, ForeignKey("jobs.id"))
    resume_id = Column(String, ForeignKey("resumes.id"))
    status = Column(String, default="pending")
    cover_letter_content = Column(Text)
    response_data = Column(JSON)
    applied_at = Column(DateTime, default=datetime.utcnow)

    user = relationship("User", back_populates="applications")
    job = relationship("Job", back_populates="applications")
    resume = relationship("Resume", back_populates="applications")

class ActivityLog(Base):
    __tablename__ = "activity_logs"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(String, ForeignKey("users.id"), nullable=True)
    action_type = Column(String)
    details = Column(JSON)
    timestamp = Column(DateTime, default=datetime.utcnow)
