from sqlalchemy import Column, Integer, String, Text, Boolean, Float, DateTime, ForeignKey, JSON, Enum
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from datetime import datetime
import enum

Base = declarative_base()

class JobStatus(str, enum.Enum):
    SCRAPED = "scraped"
    MATCHED = "matched"
    APPLYING = "applying"
    APPLIED = "applied"
    REJECTED = "rejected"
    OFFER = "offer"
    IGNORED = "ignored"

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    full_name = Column(String)
    settings = Column(JSON, default={}) # preferences, api keys
    created_at = Column(DateTime, default=datetime.utcnow)

    resumes = relationship("Resume", back_populates="user")
    projects = relationship("Project", back_populates="user")
    applications = relationship("Application", back_populates="user")
    cover_letters = relationship("CoverLetter", back_populates="user")

class Job(Base):
    __tablename__ = "jobs"

    id = Column(Integer, primary_key=True, index=True)
    url = Column(String, unique=True, index=True, nullable=False)
    source = Column(String)
    title = Column(String, nullable=False)
    company = Column(String, nullable=False)
    location = Column(String)
    posted_date = Column(DateTime)
    
    # Content
    raw_text = Column(Text)
    parsed_json = Column(JSON) # Structured JD: skills, seniority, etc.
    
    # Analysis
    is_scam = Column(Boolean, default=False)
    scam_reason = Column(Text, nullable=True)
    match_score = Column(Float, default=0.0)
    match_breakdown = Column(JSON) # Breakdown of score
    
    status = Column(String, default=JobStatus.SCRAPED.value)
    scraped_at = Column(DateTime, default=datetime.utcnow)
    
    applications = relationship("Application", back_populates="job")
    projects = relationship("Project", back_populates="job")

class Resume(Base):
    __tablename__ = "resumes"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    version_name = Column(String)
    content = Column(Text, nullable=False) # Markdown or JSON representation
    is_base = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    user = relationship("User", back_populates="resumes")
    applications = relationship("Application", back_populates="resume")

class Project(Base):
    __tablename__ = "projects"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    job_id = Column(Integer, ForeignKey("jobs.id"), nullable=True) # if generated for a specific job
    
    title = Column(String, nullable=False)
    description = Column(Text)
    tech_stack = Column(JSON)
    link = Column(String)
    is_autogenerated = Column(Boolean, default=False)
    metadata_json = Column(JSON)
    added_at = Column(DateTime, default=datetime.utcnow)
    
    user = relationship("User", back_populates="projects")
    job = relationship("Job", back_populates="projects")

class CoverLetter(Base):
    __tablename__ = "cover_letters"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    job_id = Column(Integer, ForeignKey("jobs.id"))
    content = Column(Text, nullable=False)
    personality = Column(String)
    created_at = Column(DateTime, default=datetime.utcnow)

    user = relationship("User", back_populates="cover_letters")
    application = relationship("Application", back_populates="cover_letter", uselist=False)

class Application(Base):
    __tablename__ = "applications"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    job_id = Column(Integer, ForeignKey("jobs.id"))
    resume_id = Column(Integer, ForeignKey("resumes.id"))
    cover_letter_id = Column(Integer, ForeignKey("cover_letters.id"), nullable=True)
    
    status = Column(String) # submitted, interview, offer, rejected
    response_content = Column(Text)
    screenshot_url = Column(String)
    applied_at = Column(DateTime, default=datetime.utcnow)
    metadata_json = Column(JSON)
    
    user = relationship("User", back_populates="applications")
    job = relationship("Job", back_populates="applications")
    resume = relationship("Resume", back_populates="applications")
    cover_letter = relationship("CoverLetter", back_populates="application")

class DailyMetric(Base):
    __tablename__ = "daily_metrics"
    
    id = Column(Integer, primary_key=True, index=True)
    date = Column(DateTime, default=datetime.utcnow, unique=True)
    jobs_scraped = Column(Integer, default=0)
    jobs_matched = Column(Integer, default=0)
    applications_sent = Column(Integer, default=0)
    scams_detected = Column(Integer, default=0)
